フロント部分の変更：HTTP 400エラー発生時のエラー原因の表示
selelab/admin pull request #38
Opened 2021-05-05 10:44 UTC by stepney141

#37

## Todo

- サーバ部分の変更
	- HTTPステータスと一緒にエラー原因を示すメッセージ/コードを返すようにする
- フロント部分の変更
	- サーバから返ってきたエラー原因の情報を表示する

2021-05-06 11:12 UTC, Tsutomu-Ikeda requested changes
PRありがとう！
実装の考え方自体は大丈夫なので、細かいところ修正お願いします 🙇

2021-05-06 11:12 UTC, Tsutomu-Ikeda commented on front/src/utils.js
> +const getErrorMessage = function (response, cause_of_error400 = "unknown") {
400エラーのためだけに変数を用意するのもおかしいので、変数名を `error_hint` にしたほうが良いと思います。

```diff
- const getErrorMessage = function (response, cause_of_error400 = "unknown") {
+ const getErrorMessage = function (response, error_hint) {
```

デフォルトの引数を指定しなくても `undefined` になるだけなので、値を用意しなくて良いと思います。

2021-05-06 11:12 UTC, Tsutomu-Ikeda commented on front/src/utils.js
> +    "unknown": "リクエストの中で間違っている箇所が特定できません。このエラーが発生した時の状況を併せて、管理者へお問い合わせください。"
unknownのケースは親切なメッセージなようで情報量が増えていないので、単に
```
リクエストの内容が正しくありません。
```
だけで良いかなと思います。

2021-05-06 11:29 UTC, Tsutomu-Ikeda commented
FYI: i18nを使うと良いかも？

(もしすでに知っていたら読み飛ばしてください)

```js
const error400Causes = {
    "invalid_login_credentials": "メールアドレスまたはパスワードが間違っています。",
    "over_max_chars_in_description_field": "申請内容を正しく入力しているか確認して下さい。プロジェクト説明は500文字以内で入力してください。",
    "unknown": "リクエストの中で間違っている箇所が特定できません。このエラーが発生した時の状況を併せて、管理者へお問い合わせください。"
}
```

エラーメッセージを文字列化して、それに対応する日本語を引いてくるという発想は素晴らしいです。これを発展させると、ドイツ語でも英語でも好きなようにエラーメッセージを出すことができます。このために作られたのがRailsのi18nという仕組みです。YAML (or JSON)形式で辞書を作り、アプリケーション側ではキーを指定するという形式になっています。めちゃくちゃ使いやすいので各言語で実装されていて、VueにもVue i18nというフレームワークがあります。今回の対応は局所的なものですが、導入してアプリケーション全体を書き換えちゃっても良いかもしれません。

https://qiita.com/FumioNonaka/items/bb994ab520bb0b268f65

2021-05-07 06:39 UTC, stepney141 commented
@Tsutomu-Ikeda 該当箇所を修正しました！
他にi18nが活用できそうな箇所が複数あれば、今後の改修で導入したいですね

2021-05-07 13:40 UTC, Tsutomu-Ikeda requested changes
再び細かいですが、修正お願いします 🙇‍♂️

2021-05-07 13:40 UTC, Tsutomu-Ikeda commented on front/src/utils.js
> +
`cause_of_error400` を `error_hint` へ変えたので、 `error400Causes` も `japaneseErrorHints` に変えたほうが自然だと思います。

2021-05-07 13:40 UTC, Tsutomu-Ikeda commented on front/src/utils.js
> +    if (response.status == 400) {
400に限らずやるので、ここの条件式も、

```js
if (error_hint && japaneseErrorHints[error_hint]) {
```

になると思います。

2021-05-07 13:40 UTC, Tsutomu-Ikeda commented on front/src/utils.js
> +    400: "リクエストの内容が正しくありません：",
```diff
-    400: "リクエストの内容が正しくありません：",
+    400: "リクエストの内容が正しくありません。",
```

とすると、あとにメッセージが続く場合も、続かない場合も対応できます。

2021-05-08 06:52 UTC, stepney141 commented
@Tsutomu-Ikeda 再度修正しましたのでご確認お願いします！

2021-05-08 07:05 UTC, Tsutomu-Ikeda approved these changes
良いと思います！修正ありがとうございました！

2021-05-08 07:06 UTC, merged